# Generated by Django 5.0.1 on 2024-02-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Фото",
            ),
        ),
    ]
